=== anhntlse04122/asd/ass1/nhien_lieu.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->

<!ELEMENT rss (channel+)> 
   <!ELEMENT channel (title,link,description,language,generator,pubDate,lastBuildDate,item+ )>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT link (#PCDATA)> 
   <!ELEMENT description (#PCDATA)>
   <!ELEMENT language (#PCDATA)>
   <!ELEMENT generator (#PCDATA)>
   <!ELEMENT pubDate (#PCDATA)>
   <!ELEMENT lastBuildDate (#PCDATA)>
   <!ELEMENT item (title ,description, link,pubDate, guid)>
   <!ELEMENT guid (#PCDATA)>

   <!ATTLIST rss version CDATA #REQUIRED> 
   <!ATTLIST rss xmlns:atom CDATA #REQUIRED>

=== anhntlse04122/asd/ass1/nhien_lieu.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="nhien_lieu.xsl"?>


<!DOCTYPE rss SYSTEM "nhien_lieu.dtd">

<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <titles>Vietstock - RSS</titles>
        <link>http://vietstock.vn/34/hang-hoa/nhien-lieu.rss</link>
        <description>VietStock</description>
        <language>vi-vn</language>
        <generator>CAD</generator>
        <pubDate>Wed, 25 May 2016 01:38:37 GMT</pubDate>
        <lastBuildDate>Wed, 25 May 2016 01:38:37 GMT</lastBuildDate>
        <item>
            <title>Dầu đảo chiều sau 4 phiên rớt giá liên tiếp</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/25/dau-dao-chieu-sau-4-phien-sut-giam.jpg'/>Các hợp đồng dầu thô tương lai quay đầu tăng giá sau 4 phiên sụt giảm liên tiếp vào ngày thứ Ba khi các chuyên viên giao dịch cho rằng tình trạng gián đoạn nguồn cung gần đây sẽ khiến dự trữ dầu thô tại Mỹ lao dốc, MarketWatch đưa tin.]]></description>
            <link>http://vietstock.vn/2016/05/dau-dao-chieu-sau-4-phien-rot-gia-lien-tiep-34-477297.htm</link>
            <pubDate>Wed, 25 May 2016 07:10:12 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/dau-dao-chieu-sau-4-phien-rot-gia-lien-tiep-34-477297.htm</guid>
        </item>
        <item>
            <title>Dầu xuống đáy 1 tuần trước tình trạng dư cung kéo dài trên toàn cầu</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/24/dau-xuong-thap-nhat-trong-1-tuan.jpg'/>Các hợp đồng dầu thô tương lai khép phiên ngày thứ Hai tại mức thấp nhất trong 1 tuần khi mối lo lắng về sự cố gián đoạn sản xuất gần đây đã được xoa dịu, qua đó làm gia tăng kỳ vọng tình trạng dư cung toàn cầu sẽ kéo dài, MarketWatch đưa tin.]]></description>
            <link>http://vietstock.vn/2016/05/dau-xuong-day-1-tuan-truoc-tinh-trang-du-cungkeo-dai-tren-toan-cau-34-477112.htm</link>
            <pubDate>Tue, 24 May 2016 07:21:53 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/dau-xuong-day-1-tuan-truoc-tinh-trang-du-cungkeo-dai-tren-toan-cau-34-477112.htm</guid>
        </item>
        <item>
            <title>Dầu nhảy vọt hơn 3%/tuần nhờ sự cố gián đoạn sản xuất</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/21/dau-tang-hon-3-nho-tinh-trang-gian-doan.jpg'/>Các hợp đồng dầu thô tương lai khép lại tuần qua với mức tăng hơn 3% nhờ tình trạng gián đoạn sản xuất làm gia tăng kỳ vọng tình trạng dư cung toàn cầu sẽ sớm được xoa dịu, MarketWatch đưa tin.]]></description>
            <link>http://vietstock.vn/2016/05/dau-nhay-vot-hon-3tuan-nho-su-co-gian-doan-san-xuat-34-476865.htm</link>
            <pubDate>Sat, 21 May 2016 08:02:33 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/dau-nhay-vot-hon-3tuan-nho-su-co-gian-doan-san-xuat-34-476865.htm</guid>
        </item>
        <item>
            <title>Xăng RON 92 tăng 243 đồng/lít từ 15h ngày 20/05</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/20/xang20_1449327.jpg'/>Chiều 20/05, Liên Bộ Công Thương - Tài chính quyết định điều chỉnh giá các mặt hàng xăng dầu theo giá mới, được áp dụng kể từ 15h.]]></description>
            <link>http://vietstock.vn/2016/05/xang-ron-92tang-243-donglit-tu-15h-ngay-2005-34-476730.htm</link>
            <pubDate>Fri, 20 May 2016 14:48:10 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/xang-ron-92tang-243-donglit-tu-15h-ngay-2005-34-476730.htm</guid>
        </item>
        <item>
            <title>Dầu giảm nhẹ khi kỳ vọng Fed nâng lãi suất tăng cao</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/20/dau-giam-nhe-khi-ky-vong-Fed-nang-lai-suat-tang-cao.jpg'/>Các hợp đồng dầu thô tương lai giảm giá vào ngày thứ Năm do kỳ vọng Cục Dự trữ Liên bang Mỹ (Fed) sẽ nâng lãi suất đã nhấc bổng đồng USD, nhưng các hợp đồng này đã rút ngắn đà sụt giảm nhờ mối lo lắng về sự cố gián đoạn nguồn cung tại Nigeria, CNBC đưa tin.]]></description>
            <link>http://vietstock.vn/2016/05/dau-giam-nhe-khi-ky-vong-fed-nang-lai-suat-tang-cao-34-476639.htm</link>
            <pubDate>Fri, 20 May 2016 08:13:11 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/dau-giam-nhe-khi-ky-vong-fed-nang-lai-suat-tang-cao-34-476639.htm</guid>
        </item>
        <item>
            <title>Dầu quay đầu giảm giá sau biên bản họp của Fed</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/19/dau-giam-gia-sau-bien-ban-hop-cua-fed.jpg'/>Các hợp đồng dầu thô tương lai giảm giá vào ngày thứ Tư khi đồng USD tăng cao sau khi biên bản họp gần nhất của Cục Dự trữ Liên bang Mỹ (Fed) cho thấy cơ quan này có thể nâng lãi suất vào tháng 6/2016, MarketWatch đưa tin.]]></description>
            <link>http://vietstock.vn/2016/05/dau-quay-dau-giam-gia-sau-bien-ban-hop-cua-fed-34-476452.htm</link>
            <pubDate>Thu, 19 May 2016 07:47:25 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/dau-quay-dau-giam-gia-sau-bien-ban-hop-cua-fed-34-476452.htm</guid>
        </item>
        <item>
            <title>Hai ngày tới, giá xăng sẽ tăng tiếp?</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/18/2.jpg'/>Hiện doanh nghiệp kinh doanh xăng, dầu đầu mối đang lỗ khoảng 200 đồng/lít xăng (dầu). Vì thế, trong kỳ điều chỉnh tới, giá các mặt hàng này nhiều khả năng tăng tiếp.]]></description>
            <link>http://vietstock.vn/2016/05/hai-ngay-toi-gia-xang-se-tang-tiep-34-476333.htm</link>
            <pubDate>Wed, 18 May 2016 13:50:46 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/hai-ngay-toi-gia-xang-se-tang-tiep-34-476333.htm</guid>
        </item>
        <item>
            <title>Mỹ bất ngờ công bố khoản nợ do Ả Rập Xê út nắm giữ</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/18/arap.png'/>Ngày 16/5, Bộ Tài chính Mỹ lần đầu tiên công bố các khoản trái phiếu của Mỹ mà Ả Rập Xê út nắm giữ,  ở mức 116,8 tỷ USD trong tháng 3/2016, giảm gần 6% so với tháng 1/2016.]]></description>
            <link>http://vietstock.vn/2016/05/my-bat-ngo-cong-bo-khoan-no-do-a-rap-xe-ut-nam-giu-772-476298.htm</link>
            <pubDate>Wed, 18 May 2016 09:49:26 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/my-bat-ngo-cong-bo-khoan-no-do-a-rap-xe-ut-nam-giu-772-476298.htm</guid>
        </item>
        <item>
            <title>Dầu leo lên đỉnh 7 tháng</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/18/dau-leo-len-dinh-7-thang.jpg'/>Các hợp đồng dầu thô tương lai tăng giá 2 phiên liên tiếp vào ngày thứ Ba, đồng thời khép phiên tại mức cao nhất kể từ đầu tháng 10/2015 khi các chuyên viên giao dịch cho rằng sự cố gián đoạn sản lượng gần đây sẽ xoa dịu tình trạng dư cung toàn cầu, MarketWatch đưa tin.]]></description>
            <link>http://vietstock.vn/2016/05/dau-leo-len-dinh-7-thang-34-476246.htm</link>
            <pubDate>Wed, 18 May 2016 08:15:43 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/dau-leo-len-dinh-7-thang-34-476246.htm</guid>
        </item>
        <item>
            <title>Dầu vọt mạnh hơn 3% sau nhận định của Goldman Sachs</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/17/dau-vot-hon-3-len-cao-nhat-6-thang.jpg'/>Các hợp đồng dầu thô tương lai nhảy vọt hơn 3% vào ngày thứ Hai sau khi Goldman Sachs cho biết thị trường dầu đang rơi vào tình trạng thiếu cung, qua đó nhấc bổng giá nhiên liệu này. Được biết, giá dầu đã chịu áp lực từ tình trạng dư cung trong gần 2 năm qua, MarketWatch đưa tin.]]></description>
            <link>http://vietstock.vn/2016/05/dau-vot-manh-hon-3-sau-nhan-dinh-cua-goldman-sachs-34-476069.htm</link>
            <pubDate>Tue, 17 May 2016 07:35:47 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/dau-vot-manh-hon-3-sau-nhan-dinh-cua-goldman-sachs-34-476069.htm</guid>
        </item>
        <item>
            <title>Dầu rút khỏi mức cao nhất trong hơn 6 tháng</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/14/dau-rut-khoi-muc-cao-nhat-trong-6-thang.jpg'/>Các hợp đồng dầu thô tương lai giảm giá vào ngày thứ Sáu khi nhà đầu tư lo lắng đà leo dốc gần đây của giá dầu có thể khuyến khích các nhà sản xuất gia tăng sản lượng, MarketWatch đưa tin.]]></description>
            <link>http://vietstock.vn/2016/05/dau-rut-khoi-muc-cao-nhat-trong-hon-6-thang-34-475803.htm</link>
            <pubDate>Sat, 14 May 2016 09:10:11 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/dau-rut-khoi-muc-cao-nhat-trong-hon-6-thang-34-475803.htm</guid>
        </item>
        <item>
            <title>Dầu tiếp tục leo dốc trước kỳ vọng dư cung sẽ được xoa dịu</title>
            <description><![CDATA[<img alt='' width='120' height='90' src='http://image.vietstock.vn/2016/05/13/dau-tang-nhe-nho-ky-vong-tinh-trang-du-cung-suy-giam1.jpg'/>Các hợp đồng dầu thô tương lai tăng giá nhẹ trong ngày thứ Năm nhờ kỳ vọng đà sụt giảm của sản lượng dầu toàn cầu sẽ xoa dịu tình trạng dư cung, MarketWatch đưa tin.]]></description>
            <link>http://vietstock.vn/2016/05/dau-tiep-tuc-leo-doc-truoc-ky-vong-du-cung-se-duoc-xoa-diu-34-475608.htm</link>
            <pubDate>Fri, 13 May 2016 07:05:59 GMT</pubDate>
            <guid>http://vietstock.vn/2016/05/dau-tiep-tuc-leo-doc-truoc-ky-vong-du-cung-se-duoc-xoa-diu-34-475608.htm</guid>
        </item>
        <item>
            <title>Dầu vượt mốc 46 USD lên cao nhất trong hơn 6 tháng</title>
